Models/Activity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DojoActivities.Models
{
    public class Activity
    {
        public enum DurType {Days, Hours, Minutes}
        [Key]
        public int ActivityId { get; set; }
        public DateTime created_at { get; set; }
        public DateTime updated_at { get; set; }
        public string Title { get; set; }
        public DateTime TimeAndDate { get; set; }
        public int Duration { get; set; }
        public DurType DurationType { get; set; }
        public string Description { get; set; }
        public int CreatorId { get; set; }
        [InverseProperty("CreatedActivities")]
        public User Creator { get; set; }
        public List<Signup> Signedup { get; set; }

        public Activity()
        {
            Signedup = new List<Signup>();
        }
    }
}

Controllers/ActivityController.cs
using System;
using System.Linq;
using DojoActivities.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DojoActivities.Controllers
{
    public class ActivityController : Controller
    {

        private ActivityContext _context;
        private readonly DbConnector _dbConnector;

        public ActivityController(DbConnector connect, ActivityContext context)
        {
            _dbConnector = connect;
            _context = context;
        }

        private bool isLoggedIn()
        {
            int? currId = HttpContext.Session.GetInt32("currUser");
            if(currId == null)
            {
                return false;
            }
            return true;
        }

        [HttpGet]
        [Route("dashboard")]
        public IActionResult Dashboard()
        {
            if(!isLoggedIn()) return Redirect("/");
            User currUser = _context.Users.Single(user => user.UserId == (int)HttpContext.Session.GetInt32("currUser"));
            ViewBag.CurrentUser = currUser;
            ViewBag.AllActivities = _context.Activities.Include(act => act.Creator).Include(act => act.Signedup).ToList();
            ViewBag.CurrUser = (int)HttpContext.Session.GetInt32("currUser");
            return View("Dashboard");
        }

        [HttpGet]
        [Route("newactivity")]
        public IActionResult NewActivity()
        {
            if(!isLoggedIn()) return Redirect("/");
            return View("NewActivity");
        }

        [HttpPost]
        [Route("createactivity")]
        public IActionResult CreateActivity(ViewActivity newActivity)
        {
            if(!isLoggedIn()) return Redirect("/");
            if(ModelState.IsValid)
            {
                Activity activity = new Activity
                {
                    Title = newActivity.Title,
                    TimeAndDate = new DateTime(newActivity.Date.Year, newActivity.Date.Month, newActivity.Date.Day, newActivity.Time.Hour, newActivity.Time.Minute, 0),
                    Duration = newActivity.Duration,
                    Description = newActivity.Description,
                    Creator = _context.Users.Single(user => user.UserId == (int)HttpContext.Session.GetInt32("currUser")),
                    CreatorId = (int)HttpContext.Session.GetInt32("currUser")
                };
                _context.Add(activity);
                _context.SaveChanges();
                activity.created_at = DateTime.Now;
                activity.updated_at = DateTime.Now;
                _context.SaveChanges();
                return Redirect("/show/" + activity.ActivityId);
            }
            return View("NewActivity", newActivity);
        }

        [HttpGet]
        [Route("show/{id}")]
        public IActionResult ShowActivity(int id)
        {
            Activity test;
            if(!isLoggedIn()) return Redirect("/");
            try
            {
                test = _context.Activities.Include(act => act.Creator).Include(act => act.Signedup).ThenInclude(su => su.User).Single(act => act.ActivityId == id);
            }
            catch
            {
                return RedirectToAction("Dashboard");
            }
            ViewBag.Activity = test;
            ViewBag.CurrUser = (int)HttpContext.Session.GetInt32("currUser");
            return View("Show");
        }

        [HttpGet]
        [Route("join/{id}")]
        public IActionResult SignUp(int id)
        {
            Activity test;
            if(!isLoggedIn()) return Redirect("/");
            try
            {
                test = _context.Activities.Include(act => act.Creator).Include(act => act.Signedup).ThenInclude(su => su.User).Single(act => act.ActivityId == id);
            }
            catch
            {
                return RedirectToAction("Dashboard");
            }
            if(test.CreatorId == (int)HttpContext.Session.GetInt32("currUser"))
            {
                return RedirectToAction("Dashboard");
            }
            Signup signup = new Signup
            {
                UserId = (int)HttpContext.Session.GetInt32("currUser"),
                ActivityId = test.ActivityId
            };
            _context.Signups.Add(signup);
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        [HttpGet]
        [Route("leave/{id}")]
        public IActionResult Leave(int id)
        {
            Activity test;
            if(!isLoggedIn()) return Redirect("/");
            try
            {
                test = _context.Activities.Include(act => act.Creator).Include(act => act.Signedup).ThenInclude(su => su.User).Single(act => act.ActivityId == id);
            }
            catch
            {
                return RedirectToAction("Dashboard");
            }
            int cu = (int)HttpContext.Session.GetInt32("currUser");
            Signup toRemove;
            try
            {
                toRemove = _context.Signups.Single(su => su.ActivityId == test.ActivityId && su.UserId == cu);
            }
            catch
            {
                return RedirectToAction("Dashboard");
            }
            _context.Signups.Remove(toRemove);
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        [HttpGet]
        [Route("delete/{id}")]
        public IActionResult Delete(int id)
        {
            Activity test;
            if(!isLoggedIn()) return Redirect("/");
            try
            {
                test = _context.Activities.Include(act => act.Creator).Include(act => act.Signedup).ThenInclude(su => su.User).Single(act => act.ActivityId == id);
            }
            catch
            {
                return RedirectToAction("Dashboard");
            }
            int cu = (int)HttpContext.Session.GetInt32("currUser");
            Activity toRemove;
            try
            {
                toRemove = _context.Activities.Single(act => act.ActivityId == id);
            }
            catch
            {
                return RedirectToAction("Dashboard");
            }
            _context.Activities.Remove(toRemove);
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }
    }
}

Views/Activity/Dashboard.cshtml
@using System.Linq;
@using System.Collections.Generic;
@using DojoActivities.Models;
@{
    ViewData["Title"] = "Dashboard";
}
<div id="header">
    <h1 class="inlineblock">Dojo Activity Center</h1>
    <span class="floatright"><h4 class="inlineblock">Welcome, @ViewBag.CurrentUser.FirstName</h4> | <a href="/logout">Logout</a></span>
</div>
<table>
    <tr>
        <th>Activity</th>
        <th>Date and Time</th>
        <th>Duration</th>
        <th>Event Coordinator</th>
        <th>Number of Participants</th>   
        <th>Actions</th>
    </tr>
    @{
        foreach(Activity activity in ViewBag.AllActivities)
        {
            <tr>
                <td><a href="/show/@activity.ActivityId">@activity.Title</a></td>
                <td>@activity.TimeAndDate</td>
                <td>@activity.Duration @activity.DurationType.ToString();</td>
                <td>@activity.Creator.FirstName</td>
                <td>@activity.Signedup.Count</td>
                @if(ViewBag.CurrUser == activity.CreatorId)
                {
                    <td><a href="/delete/@activity.ActivityId">Delete</a></td>
                }
                else if(((List<Signup>)(activity.Signedup)).Count() != 0)
                {
                    if(((List<Signup>)(activity.Signedup)).Where(su => su.UserId == ViewBag.CurrUser).Count() != 0)
                    {
                        <td><a href="/Leave/@activity.ActivityId">Leave</a></td>
                    }
                    else
                    {
                        <td><a href="/Join/@activity.ActivityId">Join</a></td>
                    }
                }
                else
                {
                    <td><a href="/Join/@activity.ActivityId">Join</a></td>
                }
            </tr>
        }
    }
</table>
    <a href="/newactivity"><button>Add New Activity!</button></a>
<h1></h1>

Views/Activity/NewActivity.cshtml
@{
    ViewData["Title"] = "New Activity";
}
<link rel="stylesheet" href="~/css/newActivity.css" />
<div id="header">
    <h1 class="inlineblock">Dojo Activity Center</h1>
    <span class="floatright"><a href="/dashboard">Home</a> | <a href="/logout">Logout</a></span>
</div>
<h2>Create an Activity!</h2>
@model DojoActivities.Models.ViewActivity
<form asp-controller="Activity" asp-action="CreateActivity" method="post">
    <span asp-validation-for="Title" ></span>
    <label asp-for="Title" class="floatleft">Title: </label>
    <input asp-for="Title"/><br/>
    <span asp-validation-for="Time" ></span>
    <label asp-for="Time" class="floatleft">Time: </label>
    <input asp-for="Time"/><br/>
    <span asp-validation-for="Date" ></span>
    <label asp-for="Date" class="floatleft">Date: </label>
    <input asp-for="Date"/><br/>
    <span asp-validation-for="Duration" ></span>
    <label asp-for="Duration" class="floatleft">Duration: </label>
    <input asp-for="Duration"/>
    <select name="DurationType">
        <option value="0">Days</option>
        <option value="1">Hours</option>
        <option value="2">Minutes</option>
    </select>
    <span asp-validation-for="Description"></span>
    <label asp-for="Description" class="floatleft">Description: </label>
    <textarea name="Description"></textarea><br/>
    <input type="submit" value="Create Activity">
</form>

Views/Activity/Show.cshtml
@using System.Linq;
@using System.Collections.Generic;
@using DojoActivities.Models;
@{
    ViewData["Title"] = ViewBag.Activity.Title;
}
<div id="header">
    <h1 class="inlineblock">Dojo Activity Center</h1>
    <span class="floatright"><a href="/dashboard">Home</a> | <a href="/logout">Logout</a></span>
</div>
<span><h2>@ViewBag.Activity.Title</h2> 
@{
    if(ViewBag.CurrUser == ViewBag.Activity.CreatorId)
    {
        <a href="/delete/@ViewBag.Activity.ActivityId" class="floatright"><button>Delete</button></a>
    }
    else if(((List<Signup>)(ViewBag.Activity.Signedup)).Count() != 0)
    {
        if(((List<Signup>)(ViewBag.Activity.Signedup)).Where(su => su.UserId == ViewBag.CurrUser).Count() != 0)
        {
            <a href="/leave/@ViewBag.Activity.ActivityId" class="floatright"><button>Leave</button></a>
        }
    }
    else
    {
        <a href="/join/@ViewBag.Activity.ActivityId" class="floatright"><button>Join</button></a>
    }
}
</span>
<p>Event Coordinator: @ViewBag.Activity.Creator.FirstName</p>
<p>Description: @ViewBag.Activity.Description</p>
<p>Participants:</p>
<ul>
    @{
        foreach(DojoActivities.Models.Signup su in ViewBag.Activity.Signedup)
        {
            <li>@su.User.FirstName</li>
        }
    }
</ul>